/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_yj_homebasic_fragment_FragmentCollect */

#ifndef _Included_com_yj_homebasic_fragment_FragmentCollect
#define _Included_com_yj_homebasic_fragment_FragmentCollect
#ifdef __cplusplus
extern "C" {
#endif
#undef com_yj_homebasic_fragment_FragmentCollect_SCAN_PRRIOD
#define com_yj_homebasic_fragment_FragmentCollect_SCAN_PRRIOD 10000i64
/*
 * Class:     com_yj_homebasic_fragment_FragmentCollect
 * Method:    process_Data
 * Signature: ([D)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_com_yj_homebasic_fragment_FragmentCollect_process_1Data
  (JNIEnv *, jobject, jdoubleArray);

#ifdef __cplusplus
}
#endif
#endif
