/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_yj_homebasic_fragment_FragmentCollect_MyHandler */

#ifndef _Included_com_yj_homebasic_fragment_FragmentCollect_MyHandler
#define _Included_com_yj_homebasic_fragment_FragmentCollect_MyHandler
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
